export class AssetListModel {
    PageSize?: number;
    CurrentPage?: number;
    UserId: string;
    IsAdmin: boolean;
    HierarchyTypeCode: string;
    OwnerAssetId: string;
    AssetId: string;
    AssetType: string;
    AssetCode: string;
    AssetStatus: string;
    Address: string;
    OrderBy: string;
    OrderType: string;
    Portal: string;
    PostCode: string;
    AsbestosStatus: string;
    Auth: boolean;
    ShowAsbestos:boolean;
    ServiceAssetId :string;
    ShowService : boolean;
    Setcode:string;
    Concode:string;
    Secocode:string;
    Sescode:string;
    SimCompliance:string;
    StartDate:string;
    EndDate:string;
    EPCOnly : boolean;
    SAPBands : string;
    EPCStatus : string;
    TaskAsset:boolean;
    TaskAssets:any;
    ShowCharacteristics:boolean;

    AssetChar1:string;
    AssetChar2:string;
    AssetChar3:string;
    ChaCode1:string;
    ChaCode2:string;
    ChaCode3:string;
}